### ISSUE TITLE
Revision validation

### ISSUE THREAD

**Issue by moshue** [kcjuntunen/deprecated_ArchivePDF#10]
The validation code that checks revision comes after save/rebuild, resulting in wasted time if the user has missed the step of adding an AA revision to the drawing. Recommend checking revision first before taking any other action.

**Comment by kcjuntunen** [comment]
I finally got around to this. Enough fiddling with the code has happened that I'm deprecating this repo, and starting a fresh one [here](https://github.com/kcjuntunen/ArchivePDF). You'll the effect in the next version of the Redbrick.
